DROP TABLE IF EXISTS `t_attach`;
CREATE TABLE `t_attach` (
  `T_ID` int(10) NOT NULL AUTO_INCREMENT,
  `T_NAME` varchar(50) DEFAULT NULL,
  `T_PATH` varchar(100) DEFAULT NULL,
  `T_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`T_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;